- name: Setup the guest OS
  gather_facts: yes
  hosts: local
  become: yes
  tasks:
  - name: パッケージのインストール
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - gcc
        - make
